server:
  port: 8080
  servlet:
    multipart:
      max-request-size: 5GB
      max-file-size: 1GB
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${mysql.addr:101.35.43.156:3306}/oss?useSSL=false&amp&serverTimezone=UTC
      username: ${mysql.username:root}
      password: ${mysql.password:123abc456}
  redis:
    host: ${redis.ip:192.168.50.236}
    port: ${redis.port:6379}
    timeout: 1000
    password:
    lettuce:
      pool:
        minIdle: 30
        maxIdle: 500
        maxWait: 10000
        maxActive: 500
  application:
    name: oss-service


mybatis-plus:
  global-config:
    db-config:
      table-prefix:
      id-type:
    banner: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true



logging:
  level:
    ccw.serviceinnovation.oss.mapper: info

myoss:
  package: ccw.serviceinnovation.oss
  controller: ccw.serviceinnovation.oss.controller
  apiBatPath: D:\API文档\api\upload.bat
  postman_token: 2

dubbo:
  consumer:
    timeout: 30000
    retries: 0
  protocol:
    id: dubbo
    name: dubbo
    port: ${dubbo.protocol.port:8085}
    host: ${dubbo.protocol.host:192.168.50.236}

  scan:
    basePackages: ccw.serviceinnovation.oss
  application:
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
    #可选值 interface、instance、all，默认是 interface，即只注册接口级地址
#    register-mode: all
    #只消费应用级
#    service-discovery:
      # FORCE_INTERFACE，只消费接口级地址，如无地址则报错，单订阅 2.x 地址
      # APPLICATION_FIRST，智能决策接口级/应用级地址，双订阅
      # FORCE_APPLICATION，只消费应用级地址，如无地址则报错，单订阅 3.x 地址
#      migration: APPLICATION_FIRST
    name: oss-service-consumer
  registry:
    address: nacos://${nacos.addr:192.168.50.236:8848}
    username: ${nacos.username:nacos}
    password: ${nacos.password:nacos}


rocketmq:
  addr: ${rocketmq.addr:192.168.50.236:9876}
