server:
  port: 5555
  address: 0.0.0.0
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${mysql.addr:101.35.43.156:3306}/oss?useSSL=false&amp&serverTimezone=UTC
      username: ${mysql.username:root}
      password: ${mysql.password:123abc456}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务名小写
      routes:
        - id: oss-data-server1  #路由的ID，没有固定规则但求唯一，建议配合服务名
          uri: lb://oss-data-server     # 匹配后提供服务的路由地址，lb代表从注册中心获取服务，且以负载均衡方式转发
          predicates:
            - Path=/test/** #断言，路径相匹配的进行路由
        - id: oss-data-server  #路由的ID，没有固定规则但求唯一，建议配合服务名
          uri: lb://oss-data-server     # 匹配后提供服务的路由地址，lb代表从注册中心获取服务，且以负载均衡方式转发
          predicates:
            - Path=/object/** #断言，路径相匹配的进行路由
mybatis-plus:

  global-config:
    db-config:
      table-prefix:
      id-type:
    banner: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
