server:
  port: ${server.port:5700}
  address: 0.0.0.0


position: ${position:D:\OSS\cold_01}

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${redis.addr:101.35.43.156:3306}/oss?useSSL=false&amp&serverTimezone=UTC
      username: ${redis.username:root}
      password: ${redis.password:123abc456}
  redis:
    host: ${redis.ip:192.168.50.236}
    port: ${redis.port:6379}
    timeout: 1000
    password:
    lettuce:
      pool:
        minIdle: 5
        maxIdle: 200
        maxWait: 10000
        maxActive: 8
  application:
    name: oss-cold-data-server



