server:
  port: ${server.port:8021}
  address: ${server.address:0.0.0.0}

group: ${group:group1}
cluster: ${cluster:192.168.50.236:8031,192.168.50.236:8032,192.168.50.236:8033}
position: ${position:D:\\oss\\00\\position}
jraft-data-path: ${jraft-data-path:D:\\oss\\00\\jraft_data_path}
rpc-addr: ${rpc-addr:192.168.50.236:8031}

dubbo:
  provider:
    timeout: 30000
    retries: 0
  protocol:
    port: ${dubbo.protocol.port:-1}
    name: dubbo
    host: ${dubbo.protocol.host:192.168.50.236}
  scan:
    basePackages: ccw.serviceinnovation.ossdata
  application:
    name: oss-data-provide
    register-mode: instance
  registry:
    address: nacos://${nacos.addr:192.168.50.236:8848}?registry-type=service
    username: ${nacos.username:nacos}
    password: ${nacos.password:nacos}

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  redis:
    host: ${redis.ip:192.168.50.236}
    port: ${redis.port:6379}
    timeout: 1000
    password:
    lettuce:
      pool:
        minIdle: 5
        maxIdle: 200
        maxWait: 10000
        maxActive: 8
  application:
    name: oss-data-server


